# Sun Panel 生产环境部署配置
# 适用于生产环境的完整配置

version: '3.8'

services:
  sun-panel-navigation:
    image: baofen14787/sun-panel-navigation:latest
    container_name: sun-panel-navigation
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # 数据持久化
      - ./data:/app/data
      - ./images:/app/images
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=Asia/Shanghai
    networks:
      - sun-panel-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 可选：Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: sun-panel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - sun-panel-navigation
    networks:
      - sun-panel-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sun-panel-network:
    driver: bridge

# 可选：数据备份服务
# volumes:
#   sun-panel-data:
#     driver: local
#   sun-panel-images:
#     driver: local
